Rakesh9100/Click-The-Edible-Game

- style.css
#1 🛠️ 
- [] New feature (styling has been updated,hover effect color, text and heading colors added )
- [Yes] My code follows the style guidelines of this project
- [Yes] I have performed a self-review of my own code
- [yes] I have added demonstration in the form of GIF/video file
- [yes] I am an Open Source Contributor
Hover color updated
Basic coloring updated:-
> Styling enhanced

- index.html
- script.js
- style.css
A home icon is added to the webpage which refreshes the page on being clicked.
- [Y] New feature (non-breaking change which adds functionality)
- [Y] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my own code
- [Y] I have added demonstration in the form of GIF/video file
- [Y] I am an Open Source Contributor
Home icon on the bottom right refreshes the page on being clicked
The button doesn't execute the operation while the game is being played else the fruit count will get logically disturbed it works for all other conditions.
> Updated home icon

- README.md
Closes #25 
Added contributors section in readme file
> Added contributors to readme.md

- script.js
Closes #27 
script.js was modified to fix restart button.
when restart button is clicked:
- timer is reset
- score is set to 0
- all previously generated edibles are removed
- new edibles are generated consistently (game restarts)
The above fix has been tested thoroughly.
Demonstration video: https://imgur.com/a/hOZ8les
> Fix - Restart Button (#27)

- index.html
- script.js
Closes #32 
Issues i have worked on are:
1) I have corrected the spelling of guava in index.html
2) added the an event listener which checks if space key is pressed or not , if space key is pressed and game is running it will pause the game and again pressing the space key will resume the game.
3) to make sure that if user press the space key at home screen then pause menu doesn't open up , i have initialized "isRunning" variable by -1 thus event listener will only work when isRunning is either 1(playing) or 0(paused) and not on home screen.
> Pause by space key

- index.html
- script.js
- style.css
Fixed issue #19 
1. Changed UI.
2. Made dark and light themes.
3. Fixed the home button location.
4. Home button is redirected to reload page, not the GitHub deployed website.
> #19 issue  resolved.

- index.html
- script.js
- style.css
> #33 issue solved : Added Back icon and Removed Home icon

- assets/main.css
- assets/main.html
- assets/main.js
- index.html
- style.css
Closes #8
Game is made fully responsive . Responsive issue is fixed.
- [] Bug fix (non-breaking change which fixes an issue) - functionality of website
- [] New feature (non-breaking change which adds functionality) - Responsiveness
Tested in various Dimensions (px) : 1024 * 940 , 768 * 705 , 425 *705 px.
- [] My code follows the style guidelines of this project 
> fully responsive

- style.css
Closes #48 
https://user-images.githubusercontent.com/84455686/219884043-7e365908-5aa0-450e-bc89-586ca883fcbb.png
https://user-images.githubusercontent.com/84455686/219884068-64ed2776-e15b-4e6b-90ab-6e3684b673c4.png
> #48 issue: Background changed

- .github/workflows/bot.yaml
- bot.py
Adding a bot to automatically comment when a PR is merged.
> Custom bot message

- assets/main.css
- assets/main.html
Closes #66 
Closes #
I will add footer in the website of click the edible game under jwoc.
Added footer
> Add Footer

- assets/main.css
- assets/main.html
Closes #70
Selecting the text and images or right-clicking anyway on the game screen is so annoying and creates disturbances to the user.
- [] Bug fix (No right-click menu appears)
- [] Bug fix (No text can be selected)
- 
You cannot select any text or other components on this site and can't get the right-click menu anywhere.
Before:::
> #70 issue solved

- assets/main.js
> Prevented refresh while playing

- assets/main.css
- assets/main.html
- assets/main.js
Deciding a final score when Game Overs.
Closes #81 
This PR will add functionality of **Gameover** when certain time limit passes. (for instance say 30s). 
https://user-images.githubusercontent.com/90945182/222418942-bae54190-9f34-4d55-84ab-e0799691d533.mp4
> Added Gameover Functionality

- assets/main.css
- assets/main.html
> footer updated

- assets/main.css
- assets/main.html
- assets/main.js
This PR will add functionality of showing **Instructions** on button click.
[demo9.webm](https://user-images.githubusercontent.com/90945182/222687851-aa8b24e9-6b15-4cff-97c4-de8589b6bacb.webm)
> Added Game Instructions for the Game

- assets/main.css
- assets/main.html
- assets/main.js
With this PR, the player will be able to choose Gameplay Time while playing the game. 
Closes #97 
- I have added a function `chooseGameplayTime()` that will be triggered when the game starts.
- The player will be able to choose time based on his/her wish
- I've manipulated timer with the help of time chosen by the player.
- Eventually I've run the `decreasetime` function that decreases time periodically.
[demo24.webm](https://user-images.githubusercontent.com/90945182/223735695-cf46248d-85d4-46b4-ab19-057345df3e56.webm)
> Added Gameplay Time Functionality

- assets/main.css
> Fixed Dark mode. Issue #105

- README.md
Closes #116
I have fixed the link.
> link fixed

- assets/main.html
- assets/main.js
[demo46.webm](https://user-images.githubusercontent.com/90945182/224564624-076aadd4-5a57-4288-8ae9-27c0bfe5ff2d.webm)
> 108 highscore

- assets/main.html
- assets/main.js
Added functionality to display all scores in descending order.
Closes #123
> [Feature] Added Functionality to Display Scores in Descending order

- README.md
- assets/main.css
- assets/main.html
- assets/main.js
Closes #132 
1. **Customizable GamePlay Time**: I have modified the "Choose GamePlay Time" section to allow users to select any time duration between 30 seconds and 5 minutes. This enhancement provides users with more flexibility in choosing their preferred game duration.
2. **Updated Game Logic**: To accommodate the change in customizable time duration, I have updated the game logic (main.js under assets/) to ensure that the selected time is reflected accurately in the gameplay. This includes adjusting time tracking.
3. **Maintained Responsiveness**: I've taken care to ensure that the game remains responsive across different devices and screen sizes. The changes made to the "Choose GamePlay Time" section and the overall game interface should adapt well to various screen dimensions.
I …
> Feature Enhancement: Customizable GamePlay Time Duration

- assets/main.css
Closes #161 
Fixed the position score card by adjusting main.css
> Fix: Fixed position of score

- assets/main.css
#160 Feature Enhancement
Include Pause button animation and light icon hover effect + css
- pause button animation
- light icon hover effect and color
https://github.com/Rakesh9100/Click-The-Edible-Game/assets/65588552/1a20cd43-5bd2-4629-a1fb-25e3c4f4ff52
https://github.com/Rakesh9100/Click-The-Edible-Game/assets/65588552/a1f9115b-c4f4-4d1b-b75f-99e66169a1ea
> Pause button animation and light icon hover effect

- assets/main.css
Closes #162 
While playing game user can able to drag items of games which ruining the enjoyment of game. So now user can't drag it , making game more fun
* Firstly on local host
* Also deploy on github pages 
And it's working fine ✅
https://github.com/Rakesh9100/Click-The-Edible-Game/assets/126979961/af634aab-75c8-430d-bfac-c93b78e4a124
> Dragging bug fix

- assets/main.html
Closes #174 
Automated the copyright year, so that it need not be changed every year.
Ran the website after making necessary changes.
> [Fix] : Automating the copyright year

- assets/main.css
- assets/main.html
- assets/main.js
This PR resolved the issue: #166 
Closes #166 
[screen-capture (14).webm](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73214455/6b582586-6d7e-4ae0-8efa-fc1f1f124afd)
> Added interactive mouse pointer

- assets/main.css
- assets/main.html
- package-lock.json
Closes #180
No extra dependencies are required. The footer is no longer overlapping with the edible section components. Changes were made in main.html
1) Open the the repository on your text editor (for eg, VS code)
2) Click on Live Server
3) Navigate to Local host .
4) Click on "Play game"
5) Now the scroll the webpage, you will notice that there is no overlapping between footer and edible icons.
> Fixed the overlapping of footer with edible components

- assets/main.js
Issue Title: Adjust The No Of Bomb With Icon
Issue no: #173 
Close: #173    
I Have updated the JavaScript Code To balance The Bomb With the Icon. The WebSite According To The Project And Test It For Different Devices As It Works Well.
- Provided explanations for each section.
- Detailed Description:
- Update The JavaScript Codde To Balance The Bomb With The Icon
> No. of bombs increased with the time

- assets/main.css
- assets/main.html
- assets/main.js
Issue Title: Adjust The No Of Bomb With Icon
Issue no: #169
Close: #169     
I Have Added a Music Toggle Button and updated the JavaScript Code To Control The Autoplay Restrictions. The WebSite According To The Project And Test It For Different Devices As It Works Well.
- Provided explanations for each section.
- Detailed Description:
- Added Music Toggle  Button
- Update The JavaScript Code To Control The Autoplay Restrictions
> Add Event Listener And Music Toggle Icon

- assets/main.css
Closes #187 
The navbar has been fixed. A hover effect is added on the back button and the overflow of the instructions, light and back button has been removed.
> Updated the navbar

- assets/main.css
- assets/main.html
- assets/main.js
Issue Title: Add Back To Top Button
Issue no: #171 
Close: #171 
- Added meta information to improve SEO and rendering compatibility.
- Organized the HTML code for better readability.
- Provided explanations for each section.
- Detailed Description:
- Added Media Queries
- Added Favicon
- Added Back To Top Button
> Added Progress Indicator With Back-Top Button

- assets/main.css
Added color of the site pause menu @Rakesh9100  made it beautiful
Closes #182 
> Enhanced the look of pause box

- assets/main.css
- assets/main.html
Closes #190
Improved the UI for the instruction page , added animations, gradient, colors, styling padding etc. 
Please add the difficulty level @Rakesh9100 , and iwoc24 tag. I would really appreicate a medium tag i you likeit. Thankyou.
> Feature : Instructions box beautified

- assets/main.css
- assets/main.html
Closes #203 
A cursor inconsistency issue has been identified. The game utilizes a circular cursor, but for specific options, the arrow cursor is displayed upon hover. 
Completely Tested in Local Environment.
> Fix: Dual cursor inconsistency

- assets/main.css
- assets/main.html
Closes #210 
Instruction box is made responsive for all the screen size
https://z55ui8khzf.vmaker.com/record/x7BYNf5wtPS0sHEd
> Instruction box made responsive

- assets/main.css
- assets/main.html
- assets/main.js
This pull request addresses issue #219 by introducing a Drag & Drop feature, providing users with a seamless and interactive way to upload content. Additionally, the Upload Section has undergone a redesign to improve its visual appeal and usability.
Closes #219 
- Added a Drag & Drop feature to enhance user experience.
- Implemented a redesign of the Upload Section for a more intuitive and modern look.
I have done Alpha, Beta & Unit Testing
> Added Drag & Drop Feature and Redesigned the Upload Section

- assets/main.html
- assets/main.js
Closes #237 
As we need transparent image So we have to upload PNG files only because jpg or jpeg gives default white background.
> Image upload format issue fixed
